apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config-job-config
  namespace: gitlab
data:
  CLUSTER: "atlantis"  # Change this to configure different clusters: atlantis, central, gotham, madripoor, metropolis, wakanda
  GITLAB_NAMESPACE: "gitlab"
  GITOPS_REPO_URL: "https://github.com/rh-opencodequest/gitops.git"
  GITOPS_BRANCH: "main"

