# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   name: cloud-native-postgresql
#   namespace: openshift-operators
# spec:
#   channel: stable-v1.27
#   name: cloud-native-postgresql
#   source: certified-operators
#   sourceNamespace: openshift-marketplace

# ---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloudnative-pg
  namespace: openshift-operators
spec:
  channel: stable-v1
  installPlanApproval: Automatic
  name: cloudnative-pg
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cloudnative-pg.v1.28.1