apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhdh-config-job-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhdh-config-job-runner
subjects:
- kind: ServiceAccount
  name: rhdh-config-job-runner
  namespace: {{ .Values.namespace }}

