# Default values for keycloak-config-job
# Cluster name - change this to configure different clusters
# Options: atlantis, central, gotham, madripoor, metropolis, wakanda
cluster: atlantis

namespace: rhsso

keycloak:
  namespace: rhsso
  realm: openshift

gitops:
  repoUrl: "https://github.com/rh-opencodequest/gitops.git"
  branch: "main"

